#

services:
  entreprise.api.gouv.fr:
    image: mockserver/mockserver:5.15.0
    command: -proxyRemoteHost entreprise.api.gouv.fr -proxyRemotePort 443
    environment:
      MOCKSERVER_LOG_LEVEL: DEBUG
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/mockserverInitialization.json
    volumes:
      - ./entreprise.api.gouv.fr/mockserverInitialization.json:/config/mockserverInitialization.json
    ports:
      - 6200:1080
