/**
 * Adapter layer for translating between database schema and domain models.
 *
 * This is IMPURE infrastructure code that knows about the database schema.
 * It isolates domain logic from schema changes.
 */

import { schema } from "@~/identite-proconnect.database";
import type { ModerationState } from "@~/moderations/state/moderation_state";

type Moderation = typeof schema.moderations.$inferSelect;

/**
 * Translates database row to domain state.
 *
 * Current schema mapping:
 * - moderated_at === null → pending
 * - moderated_at !== null → approved (no rejection marker yet)
 *
 * @impure - Knows about database schema
 * @param db_row - Database moderation row
 * @returns Domain state representation
 */
export function to_domain_state(db_row: Moderation): ModerationState {
  // Schema: moderated_at: null = pending
  if (db_row.moderated_at === null) {
    return { status: "pending" };
  }

  // Currently no way to distinguish approved/rejected in schema
  // All moderated items are treated as approved
  // Future: Add rejected_at column to distinguish
  return {
    status: "approved",
    approved_at: new Date(db_row.moderated_at),
    approved_by: db_row.moderated_by ?? "unknown",
  };
}

/**
 * Translates domain decision to database update object.
 *
 * @impure - Knows about database schema
 * @param decision - Domain decision (approve or reject)
 * @param timestamp - ISO timestamp string (generated by caller)
 * @returns Database update object
 */
export function to_database_update(
  decision:
    | { approve: true; user: string }
    | { reject: true; user: string; reason: string },
  timestamp: string,
): { moderated_at: string; moderated_by: string } {
  if ("approve" in decision) {
    return {
      moderated_at: timestamp,
      moderated_by: decision.user,
    };
  }

  // Rejection: Currently uses same fields as approval
  // Future: Add rejected_at field to distinguish
  return {
    moderated_at: timestamp,
    moderated_by: decision.user,
    // TODO: Store reason in comment field (done by command layer)
  };
}
