#

name: 🧷 scalingo/buildpack

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  push:
    name: Sync scalingo/buildpack branch with .scalingo/buildpack folder
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        if: github.ref == 'refs/heads/main'
        with:
          commit_message: ${{ github.event.head_commit.message }}
          enable_jekyll: true # NOTE(douglasduteil): do not add .nojekyll file
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: scalingo/buildpack
          publish_dir: ./.scalingo/buildpack
          user_email: "github-actions[bot]@users.noreply.github.com"
          user_name: "github-actions[bot]"
